## Carregar e visualizar o Banco de dados

In [1]:
import pandas as pd
import numpy as np

#Adicionar/carregar os bancos de dados
#Para ler as base de dados usar o .read e a extensão
df_vendas = pd.read_csv('vendas_tech.csv')
display(df_vendas)
#Dataframe é a base de dados do pandas
df_gerentes = pd.read_excel('gerentes_lojas.xlsx')
display(df_gerentes)

C:\Users\Eduardo\AppData\Local\Temp\ipykernel_20380\3558106641.py:6: DtypeWarning: Columns (7) have mixed types. Specify dtype option on import or set low_memory=False.
  df_vendas = pd.read_csv('vendas_tech.csv')

,ID_Pedido,Data,Loja,Produto,Preco_Unitario,Qtd,Cliente,Data_Base
0,1,2023-06-08,São Paulo,Mouse Gamer,120.0,1,Cliente_4095,2025-01-01
1,2,2023-03-01,Belo Horizonte,iPhone 14,5500.0,1,Cliente_8750,NaN
2,3,2023-02-25,NaN,"Monitor 27""",1200.0,1,Cliente_14859,NaN
3,4,2024-11-19,RIO DE JANEIRO,Mouse Gamer,120.0,2,Cliente_17343,NaN
4,5,2024-01-27,Rio de Janeiro,Smartphone Samsung,2200.0,1,Cliente_23377,NaN
...,...,...,...,...,...,...,...,...
100095,94091,2023-10-20,Porto Alegre,iPhone 14,5500.0,1,Cliente_11755,NaN
100096,52883,2024-03-17,Porto Alegre,Notebook Dell,3500.0,2,Cliente_12879,NaN
100097,65070,2023-06-19,Belo Horizonte,Smartphone Samsung,2200.0,2,Cliente_8160,NaN
100098,94031,2024-06-14,Salvador,iPhone 14,5500.0,2,Cliente_28545,NaN
100099,36755,2023-01-03,São Paulo,Notebook HP,3200.0,2,Cliente_3274,NaN

             Loja   Gerente  Meta_Mensal
0       São Paulo    Carlos        50000
1  Rio de Janeiro  Fernanda        60000
2        Curitiba   Roberto        45000
3  Belo Horizonte   Juliana        55000
4          Recife    Marcos        48000
5    Porto Alegre     Pedro        42000
6        Salvador       Ana        52000

## Ferramentas de inspeção

In [ ]:
display(df_vendas) # Mostra as 5 primeiras e 5 ultimas
display(df_vendas.head(5)) # Só mostra as primeiras 5
display(df_vendas.tail(5)) # Só mostra as ultimas 5
display(df_vendas.sample(5)) # Mostra 5 linhas aleatorias pra amostra
display(df_vendas.shape) # Mostra quantas linhas e colunas
display(list(df_vendas.columns)) # mostra uma lista de colunas do banco de dados
display(df_vendas.info())
display(df_vendas.describe())

,ID_Pedido,Data,Loja,Produto,Preco_Unitario,Qtd,Cliente,Data_Base
0,1,2023-06-08,São Paulo,Mouse Gamer,120.0,1,Cliente_4095,2025-01-01
1,2,2023-03-01,Belo Horizonte,iPhone 14,5500.0,1,Cliente_8750,NaN
2,3,2023-02-25,NaN,"Monitor 27""",1200.0,1,Cliente_14859,NaN
3,4,2024-11-19,RIO DE JANEIRO,Mouse Gamer,120.0,2,Cliente_17343,NaN
4,5,2024-01-27,Rio de Janeiro,Smartphone Samsung,2200.0,1,Cliente_23377,NaN
...,...,...,...,...,...,...,...,...
100095,94091,2023-10-20,Porto Alegre,iPhone 14,5500.0,1,Cliente_11755,NaN
100096,52883,2024-03-17,Porto Alegre,Notebook Dell,3500.0,2,Cliente_12879,NaN
100097,65070,2023-06-19,Belo Horizonte,Smartphone Samsung,2200.0,2,Cliente_8160,NaN
100098,94031,2024-06-14,Salvador,iPhone 14,5500.0,2,Cliente_28545,NaN
100099,36755,2023-01-03,São Paulo,Notebook HP,3200.0,2,Cliente_3274,NaN

,ID_Pedido,Data,Loja,Produto,Preco_Unitario,Qtd,Cliente,Data_Base
0,1,2023-06-08,São Paulo,Mouse Gamer,120.0,1,Cliente_4095,2025-01-01
1,2,2023-03-01,Belo Horizonte,iPhone 14,5500.0,1,Cliente_8750,NaN
2,3,2023-02-25,NaN,"Monitor 27""",1200.0,1,Cliente_14859,NaN
3,4,2024-11-19,RIO DE JANEIRO,Mouse Gamer,120.0,2,Cliente_17343,NaN
4,5,2024-01-27,Rio de Janeiro,Smartphone Samsung,2200.0,1,Cliente_23377,NaN

,ID_Pedido,Data,Loja,Produto,Preco_Unitario,Qtd,Cliente,Data_Base
100095,94091,2023-10-20,Porto Alegre,iPhone 14,5500.0,1,Cliente_11755,NaN
100096,52883,2024-03-17,Porto Alegre,Notebook Dell,3500.0,2,Cliente_12879,NaN
100097,65070,2023-06-19,Belo Horizonte,Smartphone Samsung,2200.0,2,Cliente_8160,NaN
100098,94031,2024-06-14,Salvador,iPhone 14,5500.0,2,Cliente_28545,NaN
100099,36755,2023-01-03,São Paulo,Notebook HP,3200.0,2,Cliente_3274,NaN

,ID_Pedido,Data,Loja,Produto,Preco_Unitario,Qtd,Cliente,Data_Base
67662,67663,2023-06-20,Rio de Janeiro,Smartphone Samsung,2200.0,1,Cliente_14221,NaN
27964,27965,2023-11-14,Salvador,Cabo HDMI,40.0,5,Cliente_7985,NaN
13244,13245,2023-02-18,Curitiba,Teclado Mecânico,250.0,1,Cliente_26368,NaN
57841,57842,2024-12-17,Belo Horizonte,"Monitor 27""",1200.0,1,Cliente_10829,NaN
67828,67829,2024-03-30,Recife,Smartphone Samsung,2200.0,1,Cliente_15554,NaN

### Tratamento de dados -  Colunas, nulos, tipos de dados, padronização, duplicatas

In [ ]:
# Tratamento de colunas
# display(df_vendas["Loja"])
# display(df_vendas[["Loja", "Cliente"]])

# Colunas
df_Analise = df_vendas.drop(columns=["Data_Base"])

# Nulos
#df_Analise = df_Analise.dropna() # Excluir todas as linhas que tem 1 valor vazio
df_Analise["Loja"] = df_Analise["Loja"].fillna("Online")

# Tipos de dados
df_Analise["Data"] = pd.to_datetime(df_Analise["Data"], format="%Y-%m-%d") # Passa a coluna Data para colocar as informações de data formatada no formato datetime

# Padronização
df_Analise["Loja"] = df_Analise["Loja"].str.strip() # Remove espaços inuteis
df_Analise["Loja"] = df_Analise["Loja"].str.title() # Primeira letra de cada palavra maiusculo

# Encadeamento
# df_Analise["Loja"] = df_Analise["Loja"].fillna("Online").str.strip().str.title()

# Duplicatas
df_Analise = df_Analise.drop_duplicates(subset=["ID_Pedido"])

display(df_Analise)
display(df_Analise.info())

,ID_Pedido,Data,Loja,Produto,Preco_Unitario,Qtd,Cliente
0,1,2023-06-08,São Paulo,Mouse Gamer,120.0,1,Cliente_4095
1,2,2023-03-01,Belo Horizonte,iPhone 14,5500.0,1,Cliente_8750
2,3,2023-02-25,Online,"Monitor 27""",1200.0,1,Cliente_14859
3,4,2024-11-19,Rio De Janeiro,Mouse Gamer,120.0,2,Cliente_17343
4,5,2024-01-27,Rio De Janeiro,Smartphone Samsung,2200.0,1,Cliente_23377
...,...,...,...,...,...,...,...
99995,99996,2023-01-24,São Paulo,Mouse Gamer,120.0,2,Cliente_13732
99996,99997,2024-08-28,Rio De Janeiro,Cabo HDMI,40.0,1,Cliente_25058
99997,99998,2024-03-18,Curitiba,Smartphone Samsung,2200.0,2,Cliente_28864
99998,99999,2023-11-04,Porto Alegre,iPhone 14,5500.0,1,Cliente_4205
99999,100000,2024-06-15,Curitiba,Teclado Mecânico,250.0,1,Cliente_12237

<class 'pandas.core.frame.DataFrame'>
Index: 100000 entries, 0 to 99999
Data columns (total 7 columns):
 #   Column          Non-Null Count   Dtype
---  ------          --------------   -----
 0   ID_Pedido       100000 non-null  int64
 1   Data            100000 non-null  datetime64[ns]
 2   Loja            100000 non-null  object
 3   Produto         100000 non-null  object
 4   Preco_Unitario  100000 non-null  float64
 5   Qtd             100000 non-null  int64
 6   Cliente         100000 non-null  object
dtypes: datetime64[ns](1), float64(1), int64(2), object(3)
memory usage: 6.1+ MB

None

### Criar novas colunas

In [ ]:
# Faturamento
df_Analise["Faturamento"] = df_Analise["Qtd"] * df_Analise["Preco_Unitario"]


# Forma de venda
df_Analise["Forma_Venda"] = df_Analise

# Regiao



display(df_Analise)

,ID_Pedido,Data,Loja,Produto,Preco_Unitario,Qtd,Cliente,Faturamento
0,1,2023-06-08,São Paulo,Mouse Gamer,120.0,1,Cliente_4095,120.0
1,2,2023-03-01,Belo Horizonte,iPhone 14,5500.0,1,Cliente_8750,5500.0
2,3,2023-02-25,Online,"Monitor 27""",1200.0,1,Cliente_14859,1200.0
3,4,2024-11-19,Rio De Janeiro,Mouse Gamer,120.0,2,Cliente_17343,240.0
4,5,2024-01-27,Rio De Janeiro,Smartphone Samsung,2200.0,1,Cliente_23377,2200.0
...,...,...,...,...,...,...,...,...
99995,99996,2023-01-24,São Paulo,Mouse Gamer,120.0,2,Cliente_13732,240.0
99996,99997,2024-08-28,Rio De Janeiro,Cabo HDMI,40.0,1,Cliente_25058,40.0
99997,99998,2024-03-18,Curitiba,Smartphone Samsung,2200.0,2,Cliente_28864,4400.0
99998,99999,2023-11-04,Porto Alegre,iPhone 14,5500.0,1,Cliente_4205,5500.0
99999,100000,2024-06-15,Curitiba,Teclado Mecânico,250.0,1,Cliente_12237,250.0