## Carregar e visualizar o Banco de dados

In [1]:
import pandas as pd
import numpy as np

#Adicionar/carregar os bancos de dados
#Para ler as base de dados usar o .read e a extensão
df_vendas = pd.read_csv('vendas_tech.csv')
display(df_vendas)
#Dataframe é a base de dados do pandas
df_gerentes = pd.read_excel('gerentes_lojas.xlsx')
display(df_gerentes)

C:\Users\Eduardo\AppData\Local\Temp\ipykernel_20380\3558106641.py:6: DtypeWarning: Columns (7) have mixed types. Specify dtype option on import or set low_memory=False.
  df_vendas = pd.read_csv('vendas_tech.csv')

,ID_Pedido,Data,Loja,Produto,Preco_Unitario,Qtd,Cliente,Data_Base
0,1,2023-06-08,São Paulo,Mouse Gamer,120.0,1,Cliente_4095,2025-01-01
1,2,2023-03-01,Belo Horizonte,iPhone 14,5500.0,1,Cliente_8750,NaN
2,3,2023-02-25,NaN,"Monitor 27""",1200.0,1,Cliente_14859,NaN
3,4,2024-11-19,RIO DE JANEIRO,Mouse Gamer,120.0,2,Cliente_17343,NaN
4,5,2024-01-27,Rio de Janeiro,Smartphone Samsung,2200.0,1,Cliente_23377,NaN
...,...,...,...,...,...,...,...,...
100095,94091,2023-10-20,Porto Alegre,iPhone 14,5500.0,1,Cliente_11755,NaN
100096,52883,2024-03-17,Porto Alegre,Notebook Dell,3500.0,2,Cliente_12879,NaN
100097,65070,2023-06-19,Belo Horizonte,Smartphone Samsung,2200.0,2,Cliente_8160,NaN
100098,94031,2024-06-14,Salvador,iPhone 14,5500.0,2,Cliente_28545,NaN
100099,36755,2023-01-03,São Paulo,Notebook HP,3200.0,2,Cliente_3274,NaN

             Loja   Gerente  Meta_Mensal
0       São Paulo    Carlos        50000
1  Rio de Janeiro  Fernanda        60000
2        Curitiba   Roberto        45000
3  Belo Horizonte   Juliana        55000
4          Recife    Marcos        48000
5    Porto Alegre     Pedro        42000
6        Salvador       Ana        52000

## Ferramentas de inspeção

In [ ]:
display(df_vendas) # Mostra as 5 primeiras e 5 ultimas
display(df_vendas.head(5)) # Só mostra as primeiras 5
display(df_vendas.tail(5)) # Só mostra as ultimas 5
display(df_vendas.sample(5)) # Mostra 5 linhas aleatorias pra amostra
display(df_vendas.shape) # Mostra quantas linhas e colunas
display(list(df_vendas.columns)) # mostra uma lista de colunas do banco de dados
display(df_vendas.info())
display(df_vendas.describe())

,ID_Pedido,Data,Loja,Produto,Preco_Unitario,Qtd,Cliente,Data_Base
0,1,2023-06-08,São Paulo,Mouse Gamer,120.0,1,Cliente_4095,2025-01-01
1,2,2023-03-01,Belo Horizonte,iPhone 14,5500.0,1,Cliente_8750,NaN
2,3,2023-02-25,NaN,"Monitor 27""",1200.0,1,Cliente_14859,NaN
3,4,2024-11-19,RIO DE JANEIRO,Mouse Gamer,120.0,2,Cliente_17343,NaN
4,5,2024-01-27,Rio de Janeiro,Smartphone Samsung,2200.0,1,Cliente_23377,NaN
...,...,...,...,...,...,...,...,...
100095,94091,2023-10-20,Porto Alegre,iPhone 14,5500.0,1,Cliente_11755,NaN
100096,52883,2024-03-17,Porto Alegre,Notebook Dell,3500.0,2,Cliente_12879,NaN
100097,65070,2023-06-19,Belo Horizonte,Smartphone Samsung,2200.0,2,Cliente_8160,NaN
100098,94031,2024-06-14,Salvador,iPhone 14,5500.0,2,Cliente_28545,NaN
100099,36755,2023-01-03,São Paulo,Notebook HP,3200.0,2,Cliente_3274,NaN

,ID_Pedido,Data,Loja,Produto,Preco_Unitario,Qtd,Cliente,Data_Base
0,1,2023-06-08,São Paulo,Mouse Gamer,120.0,1,Cliente_4095,2025-01-01
1,2,2023-03-01,Belo Horizonte,iPhone 14,5500.0,1,Cliente_8750,NaN
2,3,2023-02-25,NaN,"Monitor 27""",1200.0,1,Cliente_14859,NaN
3,4,2024-11-19,RIO DE JANEIRO,Mouse Gamer,120.0,2,Cliente_17343,NaN
4,5,2024-01-27,Rio de Janeiro,Smartphone Samsung,2200.0,1,Cliente_23377,NaN

,ID_Pedido,Data,Loja,Produto,Preco_Unitario,Qtd,Cliente,Data_Base
100095,94091,2023-10-20,Porto Alegre,iPhone 14,5500.0,1,Cliente_11755,NaN
100096,52883,2024-03-17,Porto Alegre,Notebook Dell,3500.0,2,Cliente_12879,NaN
100097,65070,2023-06-19,Belo Horizonte,Smartphone Samsung,2200.0,2,Cliente_8160,NaN
100098,94031,2024-06-14,Salvador,iPhone 14,5500.0,2,Cliente_28545,NaN
100099,36755,2023-01-03,São Paulo,Notebook HP,3200.0,2,Cliente_3274,NaN

,ID_Pedido,Data,Loja,Produto,Preco_Unitario,Qtd,Cliente,Data_Base
67662,67663,2023-06-20,Rio de Janeiro,Smartphone Samsung,2200.0,1,Cliente_14221,NaN
27964,27965,2023-11-14,Salvador,Cabo HDMI,40.0,5,Cliente_7985,NaN
13244,13245,2023-02-18,Curitiba,Teclado Mecânico,250.0,1,Cliente_26368,NaN
57841,57842,2024-12-17,Belo Horizonte,"Monitor 27""",1200.0,1,Cliente_10829,NaN
67828,67829,2024-03-30,Recife,Smartphone Samsung,2200.0,1,Cliente_15554,NaN

### Tratamento de dados -  Colunas, nulos, tipos de dados, padronização, duplicatas

In [ ]:
# Tratamento de colunas
# display(df_vendas["Loja"])
# display(df_vendas[["Loja", "Cliente"]])

# Colunas
df_Analise = df_vendas.drop(columns=["Data_Base"])

# Nulos
#df_Analise = df_Analise.dropna() # Excluir todas as linhas que tem 1 valor vazio
df_Analise["Loja"] = df_Analise["Loja"].fillna("Online")

# Tipos de dados
df_Analise["Data"] = pd.to_datetime(df_Analise["Data"], format="%Y-%m-%d") # Passa a coluna Data para colocar as informações de data formatada no formato datetime

# Padronização
df_Analise["Loja"] = df_Analise["Loja"].str.strip() # Remove espaços inuteis
df_Analise["Loja"] = df_Analise["Loja"].str.title() # Primeira letra de cada palavra maiusculo

# Encadeamento
# df_Analise["Loja"] = df_Analise["Loja"].fillna("Online").str.strip().str.title()

# Duplicatas
df_Analise = df_Analise.drop_duplicates(subset=["ID_Pedido"])

display(df_Analise)
display(df_Analise.info())

,ID_Pedido,Data,Loja,Produto,Preco_Unitario,Qtd,Cliente
0,1,2023-06-08,São Paulo,Mouse Gamer,120.0,1,Cliente_4095
1,2,2023-03-01,Belo Horizonte,iPhone 14,5500.0,1,Cliente_8750
2,3,2023-02-25,Online,"Monitor 27""",1200.0,1,Cliente_14859
3,4,2024-11-19,Rio De Janeiro,Mouse Gamer,120.0,2,Cliente_17343
4,5,2024-01-27,Rio De Janeiro,Smartphone Samsung,2200.0,1,Cliente_23377
...,...,...,...,...,...,...,...
99995,99996,2023-01-24,São Paulo,Mouse Gamer,120.0,2,Cliente_13732
99996,99997,2024-08-28,Rio De Janeiro,Cabo HDMI,40.0,1,Cliente_25058
99997,99998,2024-03-18,Curitiba,Smartphone Samsung,2200.0,2,Cliente_28864
99998,99999,2023-11-04,Porto Alegre,iPhone 14,5500.0,1,Cliente_4205
99999,100000,2024-06-15,Curitiba,Teclado Mecânico,250.0,1,Cliente_12237

<class 'pandas.core.frame.DataFrame'>
Index: 100000 entries, 0 to 99999
Data columns (total 7 columns):
 #   Column          Non-Null Count   Dtype
---  ------          --------------   -----
 0   ID_Pedido       100000 non-null  int64
 1   Data            100000 non-null  datetime64[ns]
 2   Loja            100000 non-null  object
 3   Produto         100000 non-null  object
 4   Preco_Unitario  100000 non-null  float64
 5   Qtd             100000 non-null  int64
 6   Cliente         100000 non-null  object
dtypes: datetime64[ns](1), float64(1), int64(2), object(3)
memory usage: 6.1+ MB

None

### Criar novas colunas

In [46]:
# Faturamento
df_Analise["Faturamento"] = df_Analise["Qtd"] * df_Analise["Preco_Unitario"]

# Forma de venda
df_Analise["Forma_Venda"] = np.where(df_Analise["Loja"]=="Online", "Online", "Presencial") # é como se fosse o if (condicional)

# Regiao
display(df_Analise["Loja"].unique()) # Vai mostrar quais são os Estados unicos
dic_regioes = {
               'São Paulo': "Sudeste", 
               'Belo Horizonte': "Sudeste", 
               'Online': "Online", 
               'Rio De Janeiro': "Sudeste", 
               'Salvador': "Nordeste", 
               'Recife': "Nordeste", 
               'Curitiba': "Sul", 
               'Porto Alegre': "Sul"
               }
df_Analise["Região"] = df_Analise["Loja"].map(dic_regioes)
display(df_Analise)
display(df_Analise.isna().sum())

array(['Rio De Janeiro', 'Belo Horizonte', 'Porto Alegre', 'Online',
       'Salvador', 'Curitiba', 'São Paulo', 'Recife'], dtype=object)

,level_0,index,ID_Pedido,Data,Loja,Produto,Preco_Unitario,Qtd,Cliente,Faturamento,Forma_Venda,Região
0,0,34749,34750,2023-01-01,Rio De Janeiro,Notebook HP,3200.0,1,Cliente_9014,3200.0,Presencial,Sudeste
21,20,43235,43236,2023-01-01,Belo Horizonte,Notebook HP,3200.0,2,Cliente_9031,6400.0,Presencial,Sudeste
12,10,87486,87487,2023-01-01,Rio De Janeiro,Smartphone Samsung,2200.0,2,Cliente_29128,4400.0,Presencial,Sudeste
22,21,6427,6428,2023-01-01,Porto Alegre,iPhone 14,5500.0,10,Cliente_17114,55000.0,Presencial,Sul
30,12,12847,12848,2023-01-01,Belo Horizonte,Cabo HDMI,40.0,1,Cliente_4327,40.0,Presencial,Sudeste
...,...,...,...,...,...,...,...,...,...,...,...,...
99965,99950,80054,80055,2024-12-30,São Paulo,Smartphone Samsung,2200.0,2,Cliente_23052,4400.0,Presencial,Sudeste
99950,99951,71425,71426,2024-12-30,Curitiba,Smartphone Samsung,2200.0,1,Cliente_22210,2200.0,Presencial,Sul
99951,99957,24020,24021,2024-12-30,Belo Horizonte,Smartphone Samsung,2200.0,1,Cliente_12231,2200.0,Presencial,Sudeste
99992,99993,28532,28533,2024-12-30,São Paulo,Smartphone Samsung,2200.0,2,Cliente_5400,4400.0,Presencial,Sudeste
99999,99999,91692,91693,2024-12-30,São Paulo,iPhone 14,5500.0,1,Cliente_17362,5500.0,Presencial,Sudeste

level_0           0
index             0
ID_Pedido         0
Data              0
Loja              0
Produto           0
Preco_Unitario    0
Qtd               0
Cliente           0
Faturamento       0
Forma_Venda       0
Região            0
dtype: int64

### Analisar

In [ ]:
# Analisar - filtrar
df_Analise = df_Analise.sort_values(by=["Data", "Faturamento"])
df_Analise = df_Analise.reset_index(drop=True)

# .loc: id do pedido > Nome da coluna e nome da linha
id_pedido = 4
loja = df_Analise.loc[df_Analise["ID_Pedido"]==4, "Loja"].values[0]
produto = df_Analise.loc[df_Analise["ID_Pedido"]==4, "Produto"].values[0]
cliente = df_Analise.loc[df_Analise["ID_Pedido"]==4, "Cliente"].values[0]
print(loja, produto, cliente)

# .iloc > Por posição
id_pedido = 4
iloja = df_Analise.iloc[3, 2]
iproduto = df_Analise.iloc[3, 6]
icliente = df_Analise.iloc[3, 3]
print(iloja, iproduto, icliente)

# condicional
df_id_pedido4 = df_Analise[df_Analise["ID_Pedido"]==4]
display(df_id_pedido4)


# Exportar pedaços da base
df_vendas_sp = 

display(df_Analise)

Rio De Janeiro Mouse Gamer Cliente_17343
Porto Alegre Cliente_9348 Cabo HDMI

,ID_Pedido,Data,Loja,Produto,Preco_Unitario,Qtd,Cliente,Faturamento,Forma_Venda,Região
94166,4,2024-11-19,Rio De Janeiro,Mouse Gamer,120.0,2,Cliente_17343,240.0,Presencial,Sudeste

,ID_Pedido,Data,Loja,Produto,Preco_Unitario,Qtd,Cliente,Faturamento,Forma_Venda,Região
0,12848,2023-01-01,Belo Horizonte,Cabo HDMI,40.0,1,Cliente_4327,40.0,Presencial,Sudeste
1,95393,2023-01-01,Salvador,Cabo HDMI,40.0,1,Cliente_23137,40.0,Presencial,Nordeste
2,65076,2023-01-01,Salvador,Cabo HDMI,40.0,1,Cliente_16670,40.0,Presencial,Nordeste
3,70138,2023-01-01,Porto Alegre,Cabo HDMI,40.0,1,Cliente_9348,40.0,Presencial,Sul
4,62286,2023-01-01,Recife,Cabo HDMI,40.0,1,Cliente_11523,40.0,Presencial,Nordeste
...,...,...,...,...,...,...,...,...,...,...
99995,43207,2024-12-30,Belo Horizonte,Notebook Dell,3500.0,2,Cliente_15893,7000.0,Presencial,Sudeste
99996,94455,2024-12-30,Curitiba,Notebook Dell,3500.0,2,Cliente_17419,7000.0,Presencial,Sul
99997,86379,2024-12-30,Salvador,iPhone 14,5500.0,2,Cliente_25166,11000.0,Presencial,Nordeste
99998,60794,2024-12-30,Rio De Janeiro,Smartphone Samsung,2200.0,5,Cliente_9964,11000.0,Presencial,Sudeste
99999,35192,2024-12-30,Salvador,iPhone 14,5500.0,2,Cliente_7615,11000.0,Presencial,Nordeste